*** Variables ***
${HOME_INPUT_EMAIL}              id=floatingInput
${HOME_INPUT_PASSWORD}           id=floatingPassword
${HOME_BTN_CRIARCONTA}           xpath=//button[@type='button']
${HOME_LOGIN}                    xpath=//h1[contains(.,'Login')]
${HOME_ALERT_JACADASTRADO}       xpath=//div[contains(@role,'alert')]
${HOME_BTN_CONTA}                xpath=//a[contains(@class,'btn btn-dark btn-lg btn-banner')]